"""Slack webhook service for sending notifications"""

import logging
from typing import List, Optional

import requests

from src.config import settings

logger = logging.getLogger(__name__)


class SlackService:
    """Service for sending messages to Slack via webhook"""

    def __init__(self, webhook_url: str, channel: Optional[str] = None):
        self.webhook_url = webhook_url
        self.channel = channel or "#techbrief"

    def send_message(self, text: str, blocks: Optional[List] = None) -> bool:
        """
        Send a message to Slack

        Args:
            text: Plain text message (fallback)
            blocks: Slack Block Kit blocks (optional)

        Returns:
            True if successful, False otherwise
        """
        try:
            payload = {
                "text": text,
            }

            if blocks:
                payload["blocks"] = blocks

            response = requests.post(self.webhook_url, json=payload, timeout=10)
            response.raise_for_status()

            logger.info("✓ Slack message sent successfully")
            return True

        except Exception as e:
            logger.error(f"❌ Failed to send Slack message: {e}")
            return False

    def send_daily_report(self, skill: str, articles: List, session_duration: int) -> bool:
        """
        Send daily research report to Slack

        Args:
            skill: The skill being researched today
            articles: List of ResearchArticle objects
            session_duration: Duration of research session in seconds

        Returns:
            True if successful, False otherwise
        """
        try:
            # Build article blocks
            article_blocks = []

            for i, article in enumerate(articles[:5], 1):  # Top 5 articles
                article_blocks.append(
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": f"*{i}. {article.title}*\n_Source: {article.source}_\n{article.ai_summary_short or article.keywords or '...'}\n<{article.url}|Read more>",
                        },
                    }
                )
                article_blocks.append({"type": "divider"})

            # Remove last divider
            if article_blocks:
                article_blocks.pop()

            blocks = [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": f"📚 Daily Research Report - {skill}",
                        "emoji": True,
                    },
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": f"*Skill:*\n{skill}",
                        },
                        {
                            "type": "mrkdwn",
                            "text": f"*Articles:*\n{len(articles)}",
                        },
                        {
                            "type": "mrkdwn",
                            "text": f"*Duration:*\n{session_duration}s",
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*Status:*\n✅ Completed",
                        },
                    ],
                },
                {"type": "divider"},
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": "*Top Articles:*",
                    },
                },
            ]

            blocks.extend(article_blocks)

            # Add footer
            blocks.append(
                {
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": "🤖 Generated by TechBrief AI Research System",
                        }
                    ],
                }
            )

            text = f"📚 Daily Research Report - {skill}\n{len(articles)} articles collected and processed"

            return self.send_message(text, blocks)

        except Exception as e:
            logger.error(f"❌ Failed to send daily report: {e}")
            return False


# Global instance
slack_service = SlackService(
    webhook_url=settings.slack_webhook_url,
    channel=settings.slack_channel,
)
